name: Run tests
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions: ['7.2', '7.3']
        composer-flags: ['--prefer-lowest', '--prefer-stable']
        env:
            - LARAVEL_VERSION='5.7.*' TESTBENCH_VERSION='3.8.*'
            - LARAVEL_VERSION='5.8.*' TESTBENCH_VERSION='3.8.*'
            - LARAVEL_VERSION='^6.0'  TESTBENCH_VERSION='^6.0'
    name: Test on PHP ${{ matrix.php-versions }}, Laravel ${{ matrix.laravel-versions }} and ${{ matrix.composer-flags }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Check PHP Version
      run: php -v
    - name: Check Composer Version
      run: composer -V
    - name: Check PHP Extensions
      run: php -m
    - name: Install pre-dependencies
      run: |
        composer config discard-changes true
        composer self-update
        composer require --dev "laravel/framework:${LARAVEL}" --no-interaction --no-update
        composer require --dev "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update
    - name: Install dependencies
      run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest --no-interaction
    - name: Run PHPUnit
      run: php vendor/bin/phpunit