name: Run tests
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions: ['7.2', '7.3']
        laravel-versions: ['5.7.*', '5.8.*', '^6.0']
        composer-flags: ['--prefer-lowest', '--prefer-stable']
    name: Test on PHP ${{ matrix.php-versions }}, Laravel ${{ matrix.laravel-versions }} and ${{ matrix.composer-flags }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Check PHP Version
      run: php -v
    - name: Check Composer Version
      run: composer -V
    - name: Check PHP Extensions
      run: php -m
    - name: Install pre-dependencies
      run: |
        composer config discard-changes true
        composer self-update
        composer require --dev "laravel/framework:${{ matrix.laravel-versions }}" --no-interaction --no-update
    - name: Install dependencies
      run: composer update COMPOSER_FLAGS="${{ matrix.composer-flags }}" --no-suggest --no-interaction
    - name: Run PHPUnit
      run: php vendor/bin/phpunit