name: Run Tests

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4', '8.0', 8.1, '8.2']
        composer-flags: ['--prefer-lowest', '--prefer-stable']
        env: ["LARAVEL_VERSION='^7.0'  TESTBENCH_VERSION='^5.0'", "LARAVEL_VERSION='^8.0'  TESTBENCH_VERSION='^6.0'", "LARAVEL_VERSION='^9.0'  TESTBENCH_VERSION='^7.0'"]

    name: Test on PHP ${{ matrix.php-versions }}, Laravel ${{ matrix.laravel-versions }} and ${{ matrix.composer-flags }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Check Environment
        run: |
          ${{ matrix.env }}
          php -v
          composer -V
          php -m
          echo "Laravel version ${LARAVEL_VERSION}"
          echo "Orchestra Testbench version ${TESTBENCH_VERSION}"

      - name: Install Dependencies
        run: |
          ${{ matrix.env }}
          composer config discard-changes true
          composer self-update
          composer require --dev "laravel/framework:${LARAVEL_VERSION}" --no-interaction --no-update
          composer require --dev "orchestra/testbench:${TESTBENCH_VERSION}" --no-interaction --no-update
          composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest --no-interaction

      - name: Run PHPUnit
        run: php vendor/bin/phpunit
